name: ai-service-commerce-platform

# 先启动基础设施：docker compose -f docker-compose-environment.yml up -d
# 再启动应用：docker compose -f docker-compose-app-v1.0.yml up -d
services:
  # 部署前端项目
  group-buy-market-front:
    image: registry.cn-hangzhou.aliyuncs.com/xfg-studio/nginx:latest
    container_name: ai-service-commerce-platform-nginx
    restart: always
    ports:
      - '9001:80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
    privileged: true
    networks:
      - commerce-network

  # 部署后端项目 - 小型支付商城
  s-pay-mall-app:
    image: lipeicheng/s-pay-mall-ddd-lpc-app:1.0
    container_name: ai-service-commerce-platform-s-pay-mall-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - TZ=PRC
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8080
      - APP_CONFIG_GROUP_BUY_MARKET_API_URL=http://group-buy-market-front
      - APP_CONFIG_GROUP_BUY_MARKET_NOTIFY_URL=http://s-pay-mall-app:8080/api/v1/alipay/group_buy_notify
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/s-pay-mall?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
      - WEIXIN_CONFIG_ORIGINALID=gh_aec3b0f21ae2
      - WEIXIN_CONFIG_TOKEN=180818ly
      - WEIXIN_CONFIG_APP_ID=wx39335001840306f6
      - WEIXIN_CONFIG_APP_SECRET=d588ef20942027994721fba5aff6ed25
      - WEIXIN_CONFIG_TEMPLATE_ID=Ky9LEqquuj73KUuj8UAlKWBzR_IjujNt-t7_23SWE-E
      - ALIPAY_NOTIFY_URL=http://licodetech.top:8080/api/v1/alipay/alipay_notify_url
      - ALIPAY_RETURN_URL=http://localhost:9001/
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - commerce-network

  # 拼团，负载01
  group-buy-market-01:
    image: lipeicheng/group-buy-market-lpc-app:1.0
    container_name: ai-service-commerce-platform-group-buy-market-01
    restart: on-failure
    ports:
      - "8091:8091"
    environment:
      - TZ=PRC
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8091
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/group_buy_market?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
      - REDIS_SDK_CONFIG_HOST=redis
      - REDIS_SDK_CONFIG_PORT=6379
      - XFG_WRENCH_CONFIG_SYSTEM=group-buy-market
      - XFG_WRENCH_CONFIG_REGISTER_HOST=redis
      - XFG_WRENCH_CONFIG_REGISTER_PORT=6379
      - LOGSTASH_HOST=logstash
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - commerce-network

  # 拼团，负载02
  group-buy-market-02:
    image: lipeicheng/group-buy-market-lpc-app:1.0
    container_name: ai-service-commerce-platform-group-buy-market-02
    restart: on-failure
    ports:
      - "8092:8091"
    environment:
      - TZ=PRC
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8091
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/group_buy_market?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
      - REDIS_SDK_CONFIG_HOST=redis
      - REDIS_SDK_CONFIG_PORT=6379
      - XFG_WRENCH_CONFIG_SYSTEM=group-buy-market
      - XFG_WRENCH_CONFIG_REGISTER_HOST=redis
      - XFG_WRENCH_CONFIG_REGISTER_PORT=6379
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - commerce-network

networks:
  commerce-network:
    name: ai-service-commerce-platform-network
    external: true
